doctrine/cache

lib/Doctrine/Common/Cache/FileCache.php, lib/Doctrine/Common/Cache/FilesystemCache.php, lib/Doctrine/Common/Cache/PhpFileCache.php
* Applied fix for possible race conditions from doctrine/cache#38 to `PhpFileCache` by extracting the code into the parent class to make sure both concrete caches create the cache file the same way
* Added a line to `unlink` a created temp file in case `rename` was not successful
* Removed duplicated code and made it more consistent. For example the `FilesystemCache` tried to create a missing path in `doSave` whereas `PhpFileCache` did not.
If you prefer two or three separate pull requests for this let me know.
Issue was originally reported in piwik/piwik#6873
=> Fix race condition in PhpFileCache

lib/Doctrine/Common/Cache/RedisCache.php
Removed support for Redis::SERIALIZER_IGBINARY for HHVM compability.
This fixes failing tests and functionality against HVVM with current master and previous versions. Tested with HHVM 3.3.0, Debian 7.6 and a running app top of Symfony 2.5.
Current cache driver implementation not works with HHVM, due to serialization problems:
https://travis-ci.org/doctrine/cache/jobs/46654706#L245-L358
Additional links for HHVM changes:
https://reviews.facebook.net/D31353
https://github.com/facebook/hhvm/pull/4623 https://github.com/facebook/hhvm/commit/c7cb8899a65b68984ca72aaa9fdbeb8236343535
=> Improved support for Redis serializing against HHVM

lib/Doctrine/Common/Cache/SQLite3Cache.php
Fetching data as array [1](http://www.php.net/manual/en/sqlite3result.fetcharray.php) use SQLITE3_BOTH mode by default.
Column number association is not used anywhere in the SQLite3 cache driver, but only column name.
On large data, we can improved a bit the memory usage.
Don't forget also the https://github.com/doctrine/cache/pull/62 that is really necessary to prove that this driver is operational.
I recommand also to fixed all others binding values to avoid confusion and error.
=> Reduce memory usage in SQLite3 cache

lib/Doctrine/Common/Cache/MemcacheCache.php, tests/Doctrine/Tests/Common/Cache/MemcacheCacheTest.php
If you save a value in memcache that results in FALSE when it's cast to a boolean, then `MemcacheCache::doContains()` will not work. This PR fixes that by checking if `memcache::get()` changed the value of its 2nd parameter ("flags"). If it did, it means the value surely exists.
Example: Let's say you save an empty array in memcache. Calling `MemcacheCache::doContains()` will call `memcache::get()` internally and cast the result to boolean. Since `(bool) array()` is FALSE in PHP, `doContains` will tell you that memcache doesn't have that value, even if it's actually there.
This applies to the following values:
- 0
- 0.0
- "0"
- ""
- array()
- FALSE
- NULL
I also added a Unit-Test to make sure the behaviour is correct.
PS: This is similar to …
=> Memcache::doContains incorrectly returns FALSE for some values

lib/Doctrine/Common/Cache/PhpFileCache.php
Not sure if it's relevant, but this makes the `PhpFileCache` actually usable in a context where OpCache is enabled.
=> Improved PhpFileCache performance by removing useless stat calls

lib/Doctrine/Common/Cache/SQLite3Cache.php, tests/Doctrine/Tests/Common/Cache/SQLite3CacheTest.php
Here is a unit to demonstrate issue that truncate data.
1 - I've took the SQLite3Cache as object sample, but we can pick any other objects.
2 - I've fixed the `tearDown()` method, to close the sqlite3 DB instance before to remove file (or we got denied permission)
Without fix, you should get something like 
1) Doctrine\Tests\Common\Cache\SQLite3Test::testFetchSingle
Unexpected exception has been raised. unserialize(): Error at offset 47 of 51 bytes
=> Unit test to solve original PR#62

lib/Doctrine/Common/Cache/CacheProvider.php
Changed confusing string return type for doFetch, which *can* return string, but will generally return an object - as defined in [Cache::fetch](https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/Cache.php#L55)
=> Fix PHPDoc for doFetch return type

lib/Doctrine/Common/Cache/FileCache.php
This fixes a race condition which occurs when the directory was created between the calls to `is_dir` and `mkdir` by checking `is_dir` again after `mkdir`. If `mkdir` failed but `is_dir` return true anyway, there is no problem.
=> Fix race condition in FileCache-based drivers.

lib/Doctrine/Common/Cache/ClearableCache.php, lib/Doctrine/Common/Cache/FlushableCache.php
I was browsing the different common interfaces in Doctrine Cache and happened upon both the `Flushable` and `Clearable` interfaces and for the life of me couldn't figure out the difference between the two.
[After a quick conversation with @Ocramius][ocramius-twitter-cache-thread], he helped me understand the difference. I figured I'd improve the docs here to help clarify their intents so that others wouldn't get into the same confusion and hopefully help improve discoverability.
[ocramius-twitter-cache-thread]: https://twitter.com/trevorsuarez/status/606133921542217728
=> Enhancement - Improve Flushable/Clearable interface documentation

lib/Doctrine/Common/Cache/CacheProvider.php, tests/Doctrine/Tests/Common/Cache/CacheTest.php
This is fixing some errors when we provide an empty array to CacheProvider::fetchMultiple :
- On PHP 5.3, Both parameters of array_combine should have at least 1 element.
- If we provide an empty array, Redis mget returns false and array_combine expects parameter 2 to be array.
=> Fix CacheProvider::fetchMultiple if keys array is empty

lib/Doctrine/Common/Cache/CacheProvider.php, tests/Doctrine/Tests/Common/Cache/CacheProviderTest.php, tests/Doctrine/Tests/Common/Cache/CacheTest.php, tests/Doctrine/Tests/Common/Cache/FileCacheTest.php, tests/Doctrine/Tests/Common/Cache/SQLite3CacheTest.php
1. The namepace version is increased in deleteAll() and also saved there. So when the version is still the default (1) there is no point in persisting that. This way we save space and unneeded workload.
2. do not update the cached namespace version when persistence failed. Otherwise all data written after a failed delete, will not be available later on.
=> No need to save the default namespace version

lib/Doctrine/Common/Cache/ApcCache.php, lib/Doctrine/Common/Cache/Cache.php, lib/Doctrine/Common/Cache/FileCache.php, lib/Doctrine/Common/Cache/FilesystemCache.php, lib/Doctrine/Common/Cache/MemcacheCache.php, lib/Doctrine/Common/Cache/MemcachedCache.php, lib/Doctrine/Common/Cache/MongoDBCache.php, lib/Doctrine/Common/Cache/PredisCache.php, lib/Doctrine/Common/Cache/RedisCache.php, tests/Doctrine/Tests/Common/Cache/BaseFileCacheTest.php, tests/Doctrine/Tests/Common/Cache/CacheTest.php, tests/Doctrine/Tests/Common/Cache/FilesystemCacheTest.php, tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php, tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php, tests/Doctrine/Tests/Common/Cache/PredisCacheTest.php
1. fix delete() return value when file does not exist: it must return true even if the cache entry doesn't exist. False should only be returned in case of a failed delete. Since the outcome of deleting a non-existing entry is what we wanted anyway (the entry doesn't exist anymore), it should return true. But the filesystem cache returned false because `unlink` returns false if the file does not exist. This was also broken for some other cache drivers.
2. fix flushAll() and getStats() for file cache to ignore dot files and clean up balancing directories: before it also iterated over dot files `.` and `..` (if the extension is empty) trying to delete them, which of course failed, but was silenced. and intermediate directories for balancing were never removed. flushAll only removed the files …
=> Fix delete() and flushAll()

lib/Doctrine/Common/Cache/MongoDBCache.php
Without this commit, we sometimes have error like ```E11000 duplicate key error collection: cache.cache index: ​_id_​ dup key: { ...``` I don't know exactly what happen inside MongoDB to throw this error but the Cache interface is pretty clear that it should not throw any Exception but return a boolean to express that the cache has been saved or not
=> Avoid MongoCursorException with MongoCache

lib/Doctrine/Common/Cache/CacheProvider.php, lib/Doctrine/Common/Cache/RedisCache.php, tests/Doctrine/Tests/Common/Cache/ApcCacheTest.php, tests/Doctrine/Tests/Common/Cache/ArrayCacheTest.php, tests/Doctrine/Tests/Common/Cache/CacheTest.php, tests/Doctrine/Tests/Common/Cache/ChainCacheTest.php, tests/Doctrine/Tests/Common/Cache/CouchbaseCacheTest.php, tests/Doctrine/Tests/Common/Cache/FilesystemCacheTest.php, tests/Doctrine/Tests/Common/Cache/MemcacheCacheTest.php, tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php, tests/Doctrine/Tests/Common/Cache/MongoDBCacheTest.php, tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php, tests/Doctrine/Tests/Common/Cache/SQLite3CacheTest.php
When fixing https://github.com/doctrine/cache/pull/104/files#r43902042 I found that the `fetchMultiple` is broken, when the cached data is `false` which I fixed as well.
=> Fix fetch multiple with false

.travis.yml, lib/Doctrine/Common/Cache/FileCache.php, phpunit.xml.dist, tests/Doctrine/Tests/Common/Cache/CacheTest.php
I realised that doctrine annotation cache (which uses long cache keys) is failing in symfony under windows.
Its because in Windows the whole path is limited to 260 chars. See http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows
Also fixed travis tests with apcu due to new releases of apcu for php 5 and 7.
=> fix file cache naming under windows surpassing MAX_PATH

lib/Doctrine/Common/Cache/ApcuCache.php, tests/Doctrine/Tests/Common/Cache/ApcuCacheTest.php
Add native APCu support (replace #112).
@guilhermeblanco, I don't think that it is possible to add `apcu_entry` support without adding a new interface to Doctrine Cache.
=> Add APCu cache provider

.travis.yml, composer.json
Because http://php.net/supported-versions.php
Also: tempted to drop 5.5 as well.
=> Cleanup: drop unsupported php versions

lib/Doctrine/Common/Cache/MemcachedCache.php
The `setMulti` signature for memcached is http://php.net/manual/en/memcached.setmulti.php:
```php
public bool Memcached::setMulti ( array $items [, int $expiration ] )
```
But there are more... In the extension definition (https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c#L1252) this has a third param.
This fixes passing the `$lifetime` instead of the `udf_flags`.
=> Fix save multiple on memcached

README.md
Since this repo is linked to packagist, it would be nice to have an easy to find link to the documentation.
=> Added link to the documentation

lib/Doctrine/Common/Cache/PredisCache.php
This PR
💁 For reference, see http://redis.io/commands/EXISTS#return-value.
=> Fix: exists() returns an integer

tests/Doctrine/Tests/Common/Cache/WinCacheCacheTest.php
=> Fix: Case-insensitive class references

tests/Doctrine/Tests/Common/Cache/CacheTest.php
=> Fix: Second parameter should probably be an assertion message

tests/Doctrine/Tests/Common/Cache/SQLite3CacheTest.php
=> Fix: Class name does not match file name

lib/Doctrine/Common/Cache/ApcCache.php, lib/Doctrine/Common/Cache/ApcuCache.php, lib/Doctrine/Common/Cache/CacheProvider.php, lib/Doctrine/Common/Cache/ChainCache.php, lib/Doctrine/Common/Cache/CouchbaseCache.php, lib/Doctrine/Common/Cache/FileCache.php, lib/Doctrine/Common/Cache/MemcacheCache.php, lib/Doctrine/Common/Cache/MemcachedCache.php, lib/Doctrine/Common/Cache/MongoDBCache.php, lib/Doctrine/Common/Cache/PhpFileCache.php, lib/Doctrine/Common/Cache/PredisCache.php, lib/Doctrine/Common/Cache/RedisCache.php, lib/Doctrine/Common/Cache/SQLite3Cache.php, lib/Doctrine/Common/Cache/WinCacheCache.php, lib/Doctrine/Common/Cache/XcacheCache.php, tests/Doctrine/Tests/Common/Cache/BaseFileCacheTest.php, tests/Doctrine/Tests/Common/Cache/CacheProviderTest.php, tests/Doctrine/Tests/Common/Cache/CacheTest.php, tests/Doctrine/Tests/Common/Cache/ChainCacheTest.php, tests/Doctrine/Tests/Common/Cache/FileCacheTest.php, tests/Doctrine/Tests/Common/Cache/MongoDBCacheTest.php, tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php, tests/Doctrine/Tests/Common/Cache/PredisCacheTest.php
This PR
💁 Ran
```
$ composer global require friendsofphp/php-cs-fixer:2.0.0-alpha
$ php-cs-fixer fix --using-cache=no --rules=short_array_syntax .
```
=> Fix: Use short array syntax

lib/Doctrine/Common/Cache/SQLite3Cache.php
This PR
💁 This also makes the happy path more obvious! We're happier if we found something in the cache, aren't we?
=> Fix: Remove assignment from condition

lib/Doctrine/Common/Cache/ApcCache.php, lib/Doctrine/Common/Cache/ApcuCache.php, lib/Doctrine/Common/Cache/MemcachedCache.php, tests/Doctrine/Tests/Common/Cache/ApcCacheTest.php, tests/Doctrine/Tests/Common/Cache/ApcuCacheTest.php
1. skip apc tests if apc.enable_cli is not enabled instead of failing (unfortunately this setting cannot be enabled at runtime)
2. fix fetchMultiple implementations that can return false on failure instead of an array. I realized this when looking at the test results in #136
> 1) Doctrine\Tests\Common\Cache\ApcCacheTest::testFetchMultiple
array_key_exists() expects parameter 2 to be array, boolean given
C:\Users\fr-mktg-od\Desktop\Sites\cache\lib\Doctrine\Common\Cache\CacheProvider.php:98
=> APC skip & fix fetchMultiple on failure

lib/Doctrine/Common/Cache/PhpFileCache.php, tests/Doctrine/Tests/Common/Cache/CacheTest.php, tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php
Continues #152
Fixes #147 
This is moved to `1.7.0` only, since some people my have been relying on the error handlers.
=> Fix - #152 #147 - silence failed file access attempts in file based caches

lib/Doctrine/Common/Cache/RedisCache.php, tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
Please review and merge my pull request. If You want reproduce this is bug, You can install php-redis extension without recommends packages (php-igbinary) and write any data to Redis cache, thats all. Thanks.
=> Fix bug with not installed igbinary extension

tests/Doctrine/Tests/Common/Cache/FileCacheTest.php
Hi.
PHPUnit feature @runInSeparateProcess cannot work properly if some extensions are not available.
Step by step:
* include tests/travis/php.ini into php config
* run php7.0 `php --interactive`, you will see error/errors:
`Warning: PHP Startup: Unable to load dynamic library '...php-7.0.13/lib/php/extensions/no-debug-non-zts-20151012/mongo.so' - dlopen(...php-7.0.13/lib/php/extensions/no-debug-non-zts-20151012/mongo.so, 9): image not found in Unknown on line 0`
* now run phpunit - test set is failed
* if you remove @runInSeparateProcess  - pass!
=> Disable PHPUnit feature @runInSeparateProcess 

lib/Doctrine/Common/Cache/CacheProvider.php, lib/Doctrine/Common/Cache/MultiGetCache.php, lib/Doctrine/Common/Cache/MultiOperationCache.php, lib/Doctrine/Common/Cache/MultiPutCache.php
Since we always depend on the three interfaces there's no reason to segregate them.
And that's also important to be able to implement https://github.com/doctrine/doctrine2/issues/6241
=> Combine multi operation interfaces into a single one

lib/Doctrine/Common/Cache/MongoDBCache.php, tests/Doctrine/Tests/Common/Cache/MongoDBCacheTest.php
Fixes #139, Supersedes #140.
Instead of always creating the index on class instantiation, this solution only creates the index once per process and only if receiving an expired cache entry (indicating that the index hasn't been properly created). Overrides the lifetime test case to test index creation. My machine didn't quite remove expired entries exactly at their expiration time, so I excluded that from the test case.
=> Create expiration index when getting expired entry

composer.json, lib/Doctrine/Common/Cache/ExtMongoDBCache.php, lib/Doctrine/Common/Cache/LegacyMongoDBCache.php, lib/Doctrine/Common/Cache/MongoDBCache.php, tests/Doctrine/Tests/Common/Cache/ExtMongoDBCacheTest.php, tests/Doctrine/Tests/Common/Cache/LegacyMongoDBCacheTest.php
Fixes #142.
Creates two new internal classes containing the actual logic, one for the legacy driver, one for ext-mongodb. The existing `MongoDBCache` class just proxies all calls to the correct implementation, depending on which collection class was given in the constructor. Since constructor arguments may change in extending classes, this shouldn't cause a BC break. With 2.0, `MongoDBNGCache` will be renamed `MongoDBCache` and the old classes removed to drop support for ext-mongo.
=> Add cache provider for ext-mongodb

lib/Doctrine/Common/Cache/FileCache.php
It is apparently necessary to set the rights of the file both
before and after writing it. Depending if you write the file on a
shared storage or not.
=> Fix temp file rights on shared storage

lib/Doctrine/Common/Cache/SQLite3Cache.php, tests/Doctrine/Tests/Common/Cache/SQLite3CacheTest.php
Tests were simply not being executed because PHPUnit was considering `sqlite` as extension name (instead of `sqlite3`) and we also had a weird `return` in the constructor.
=> Improve SQLite3 adapter

.travis.yml, lib/Doctrine/Common/Cache/CouchbaseBucketCache.php, lib/Doctrine/Common/Cache/CouchbaseCache.php, tests/Doctrine/Tests/Common/Cache/CouchbaseBucketCacheTest.php, tests/Doctrine/Tests/Common/Cache/CouchbaseCacheTest.php, tests/travis/Couchbase.sh, tests/travis/php.ini
fixes #216 
hi Team,
this request adds CouchbaseBucketCache which requires `ext-couchbase:^2.3.0`.
i've updated the Travis CI build to install the Couchbase extension, and am using a Couchbase Server Docker image forked by WebPT (my employer) which auto-creates the default bucket with flush enabled.
ext-couchbase version is checked in the CouchbaseBucketCache constructor, by ensuring that the `manager` method is callable.
`ext-couchbase:^2.0,<2.3.0` does not yet have `$bucket->manager()` which is required to flush the cache pool and to pull cluster stats. we might be able to support older versions of Couchbase 2.x, but i think we might lose some functionality that is required by this library's API. 
Couchbase throws an exception on delete if a key is not found. That is handled gracefully …
=> add support for ext-couchbase:^2.3.0

.coveralls.yml, .gitattributes
Coveralls seems to have been dropped ages ago: https://coveralls.io/github/doctrine/cache
Scrutinizer is used for coverage now.
=> Drop Coveralls config

lib/Doctrine/Common/Cache/MemcacheCache.php, lib/Doctrine/Common/Cache/RiakCache.php, lib/Doctrine/Common/Cache/XcacheCache.php, phpunit.xml.dist
All of these should be dropped eventually, none works with PHP 7.1+.
=> Exclude legacy untestable drivers from coverage & mark them deprecated

lib/Doctrine/Common/Cache/RedisCache.php
As desribed [here](https://github.com/phpredis/phpredis#exists),
Since php-redis v4 states that:
> This function took a single argument and returned TRUE or FALSE in phpredis versions < 4.0.0.
We have to cast `doContains` functions with `bool` to return TRUE or FALSE.
=> Add php-redis v4 support

tests/travis/Couchbase.sh
https://github.com/couchbase/php-couchbase/commit/fb603f4b6a0ce3a34513d0233085a3b6d8e8b4f0
https://travis-ci.org/doctrine/cache/jobs/394094974#L1133
Couchbase 2.4.7 extension requires too new libcouchbase:
```
checking for libcouchbase in default path... found in /usr
checking for libcouchbase version >= 2.9.0... 0x020807
configure: error: libcouchbase greater or equal to 2.9.0 required
```
=> CI: Lock Couchbase extension to 2.4.6 to avoid dependency mismatch

lib/Doctrine/Common/Cache/RiakCache.php
As of PHP 7.2 `object` is a reserved word. Therefore, this line: https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/RiakCache.php#L8 triggers a PHP error in 7.2. This PR attempts to solve this issue by aliasing the import.
Issue: https://github.com/doctrine/cache/issues/292
=> Alias Riak\Object as RiakObject to prevent errors in PHP 7.2

composer.json, composer.lock, lib/Doctrine/Common/Cache/CouchbaseCache.php, lib/Doctrine/Common/Cache/ExtMongoDBCache.php, lib/Doctrine/Common/Cache/LegacyMongoDBCache.php, lib/Doctrine/Common/Cache/MemcacheCache.php, lib/Doctrine/Common/Cache/MemcachedCache.php, lib/Doctrine/Common/Cache/RedisCache.php, lib/Doctrine/Common/Cache/XcacheCache.php, lib/Doctrine/Common/Cache/ZendDataCache.php, phpcs.xml.dist, tests/Doctrine/Tests/Common/Cache/CouchbaseCacheTest.php, tests/Doctrine/Tests/Common/Cache/FileCacheTest.php, tests/Doctrine/Tests/Common/Cache/MemcacheCacheTest.php, tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php, tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php, tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
Bumped the composer dependencies and fixed sniffs
In order to keep current behavior with `static::$constant` vs `self::$constant` I've added the sniff `SlevomatCodingStandard.Classes.DisallowLateStaticBindingForConstants` to the exclude list.
=> Move to doctrine/coding-standard 6

lib/Doctrine/Common/Cache/RedisCache.php
PHP Redis extension 5.0.0 deprecates `delete`.
See https://github.com/phpredis/phpredis#del-delete-unlink
=> [Redis] Fix deprecation: Use `del` instead of `delete`

lib/Doctrine/Common/Cache/RedisCache.php
Redis has a feature named _pipelining_ to group commands to execute. It reduces the number of requests (TCP or Unix socket) to Redis server by sending multiple commands per 1 request. More info on Redis site: https://redis.io/topics/pipelining
In this PR I've wrapped all the commands, that are sent to Redis in loops, into pipelines. This will have a positive effect on performance of methods that are working with multiple keys (_doFetchMultiple_ and _doSaveMultiple_).
=> Changed RedisCache to use pipeline in operations with multiple keys

tests/Doctrine/Tests/Common/Cache/ExtMongoDBCacheTest.php
Fixes #326.
This definitely fixes the test failure. The only reason I have for those test failures is that if we write the record at the timestamp `1` with a lifetime of `1`, it is scheduled to expire at timestamp `2`. However, if we're close to the end of timestamp `1` (e.g. `1.98`), the record will be expired by the time we check if it's still there. This is a very specific scenario since we're running with a TTL of `1`, which isn't a production use-case. Using a TTL of `2` (and subsequently sleeping 3 seconds instead of 2) fixes the issue where expiration comes sooner than expected.
Note: not fixing in 1.9 as this is just a build system issue and we're releasing 1.10 soon anyways.
=> Fix flaky MongoDB test

lib/Doctrine/Common/Cache/InvalidCacheId.php, lib/Doctrine/Common/Cache/MemcachedCache.php, tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php
Here's the initial conversation: https://github.com/doctrine/cache/issues/208
This PR only ensures that memcached adapter provide valuable information while dealing with invalid key format.
TODO:
=> Prevent invalid memcached key to be used

tests/Doctrine/Tests/Common/Cache/MemcacheCacheTest.php
It seems to be failing only with PHP 8. This failure prevents merging
1.10.x into master and having a decent CI on that branch.
=> Skip failing test
