- lib/Doctrine/Common/Cache/PredisCache.php
- lib/Doctrine/Common/Cache/RedisCache.php
Added redis and predis MGET support
> Redis  MGET support

- .travis.yml
Reference:
http://till.klampaeckel.de/blog/archives/204-Whats-wrong-with-composer-and-your-.travis.yml.html
> Fix: use the correct targets on Travis-CI

- lib/Doctrine/Common/Cache/PredisCache.php
- lib/Doctrine/Common/Cache/RedisCache.php
- tests/Doctrine/Tests/Common/Cache/CacheTest.php
- tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php
- tests/travis/php.ini
> Fix various issues with PredisCache and RedisCache

- .travis.yml
Also `--dev` is by default over a year now.
> travis: use container based build, PHP 7 added

- lib/Doctrine/Common/Cache/FileCache.php
Fix for the directory size problem on windows
> Perform various tests on windows and this correction solved the problem

- lib/Doctrine/Common/Cache/FileCache.php
- tests/Doctrine/Tests/Common/Cache/FileCacheTest.php
> Hotfix - #113 testing/correcting hashing for windows file path length limitations

- lib/Doctrine/Common/Cache/FileCache.php
https://github.com/doctrine/cache/pull/107#issuecomment-165910117
https://bugs.php.net/bug.php?id=70943
> Path length of 259 is also not possible due to php bug

- lib/Doctrine/Common/Cache/ArrayCache.php
- tests/Doctrine/Tests/Common/Cache/ArrayCacheTest.php
I had some long-time running scripts that was heavily using the ArrayCache. After a while I got some unexpected behaviour, and at first I couldn't figure out why. Imagine my surprise when I discovered that the ttl-feature was missing, it explained a lot.
So here you have my take on how it could be implemented. I also added support for hit ratio. Let me know what you think!
> Added support for stats and ttl on ArrayCache

- lib/Doctrine/Common/Cache/RiakCache.php
- tests/Doctrine/Tests/Common/Cache/ChainCacheTest.php
> Fix: Remove unused imports

- lib/Doctrine/Common/Cache/PhpFileCache.php
- tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php
> Feature - #154 - store anything in the PhpFileCache

- tests/Doctrine/Tests/Common/Cache/BaseFileCacheTest.php
- tests/Doctrine/Tests/Common/Cache/FileCacheTest.php
> Fix #187 - test suite attempts to delete `/tmp`

- lib/Doctrine/Common/Cache/CacheProvider.php
- lib/Doctrine/Common/Cache/Exception/LifeTimeException.php
- tests/Doctrine/Tests/Common/Cache/CacheTest.php
- tests/Doctrine/Tests/Common/Cache/Exception/LifeTimeExceptionTest.php
> Raise exception when trying to assign a negative value

- lib/Doctrine/Common/Cache/ApcuCache.php
- lib/Doctrine/Common/Cache/CacheProvider.php
- lib/Doctrine/Common/Cache/PredisCache.php
- lib/Doctrine/Common/Cache/RedisCache.php
- lib/Doctrine/Common/Cache/WinCacheCache.php
This basically gets the APCu and Redis changes from #186 and adds multi delete to Predis and wincache too.
> Implement multi delete on drivers

- .scrutinizer.yml
- .travis.yml
- lib/Doctrine/Common/Cache/RedisCache.php
Starting HHVM support removal on our repos, related to doctrine/doctrine2#6424
> Drop HHVM support

- lib/Doctrine/Common/Cache/CacheProvider.php
- tests/Doctrine/Tests/Common/Cache/CacheProviderTest.php
Fixes https://github.com/doctrine/doctrine2/pull/6646 and https://github.com/doctrine/doctrine2/issues/6645.
> Fix corrupted namespace

- composer.json
- tests/Doctrine/Tests/Common/Cache/ArrayCacheTest.php
- tests/Doctrine/Tests/Common/Cache/BaseFileCacheTest.php
- tests/Doctrine/Tests/Common/Cache/CacheProviderTest.php
- tests/Doctrine/Tests/Common/Cache/CacheTest.php
- tests/Doctrine/Tests/Common/Cache/ChainCacheTest.php
- tests/Doctrine/Tests/Common/Cache/ExtMongoDBCacheTest.php
- tests/Doctrine/Tests/Common/Cache/FileCacheTest.php
- tests/Doctrine/Tests/Common/Cache/FilesystemCacheTest.php
- tests/Doctrine/Tests/Common/Cache/LegacyMongoDBCacheTest.php
- tests/Doctrine/Tests/Common/Cache/MemcacheCacheTest.php
- tests/Doctrine/Tests/Common/Cache/MemcachedCacheTest.php
- tests/Doctrine/Tests/Common/Cache/PhpFileCacheTest.php
- tests/Doctrine/Tests/Common/Cache/PredisCacheTest.php
- tests/Doctrine/Tests/Common/Cache/RedisCacheTest.php
- tests/Doctrine/Tests/Common/Cache/RiakCacheTest.php
- tests/Doctrine/Tests/Common/Cache/SQLite3CacheTest.php
- tests/Doctrine/Tests/Common/Cache/VoidCacheTest.php
- tests/Doctrine/Tests/Common/Cache/ZendDataCacheTest.php
- tests/Doctrine/Tests/DoctrineTestCase.php
> Upgrade PHPUnit

- composer.json
> Change homepage link to https

- .gitattributes
Also, re-order .gitattributes alphabetically.
> Don't ship docs

- docs/en/index.rst
> MemcacheCache typo fix

- README.md
Fixes issue mentioned by @Majkl578 here https://github.com/doctrine/cache/pull/294#pullrequestreview-183001686
> point to the current version of the docs

- lib/Doctrine/Common/Cache/RedisCache.php
- lib/Doctrine/Common/Cache/Version.php
Release [1.8.2](https://github.com/doctrine/cache/milestone/21)
1.8.2
=====
- Total issues resolved: **0**
- Total pull requests resolved: **1**
- Total contributors: **1**
Bug
---
- [319: Backport #293 into 1.8.x](https://github.com/doctrine/cache/pull/319) thanks to @reedy
> Merge release 1.8.2 into master

- lib/Doctrine/Common/Cache/RedisCache.php
@Ocramius here is new PR with changed destination. And thanks for all the good work! :)
Duplicates #329
> Fix typo in `Redis` cache implementation

- lib/Doctrine/Common/Cache/RedisCache.php
Release [1.9.1](https://github.com/doctrine/cache/milestone/23)
1.9.1
=====
- Total issues resolved: **0**
- Total pull requests resolved: **1**
- Total contributors: **1**
Bug
---
- [330: Fix typo in `Redis` cache implementation](https://github.com/doctrine/cache/pull/330) thanks to @jandlouhy
> Merge release 1.9.1 into master

- docs/en/index.rst
Change "MemecacheCache" to "MemcacheCache"
> Fix typo error

- README.md
> Set documentation link to Doctrine cache

- .github/workflows/release-on-milestone-closed.yml
Although the package is going to be deprecated, we will need to make some releases to achieve that.
> Setup release workflow
